import "@/app/globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html >
      <body className="bg-[url('/next.png')] justify-center items-center bg-opacity-20 mx-auto shadow-lg  -mb-10">{children}</body>
    </html>
  )
}
