import Head from "next/head";
import "@/app/globals.css";
import Nav from "./nav/page";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (<html>
   
    <Head>
      <title>Memory cards Game</title>
      <meta name="Memory cards Game" content="Memory cards Game" />
         </Head>

  <body>
    <Nav/>
       {children}
  </body>
  </html>

  )
}
