import styles from "./Home.module.css";

import Head from "next/head";
import "./globals.css";
import Nav from "./nav/page";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (<html>
   
    <Head>
      <title>Tic Tac Toe game</title>
      <meta name="description" content="Generated by create next app" />
     
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Indie+Flower');
      </style>
    </Head>

  <body>
    <Nav/>
     <div className={styles.container}>
  <main className={styles.main}>
      {children}
    </main>
  </div>
  </body>
  </html>

  )
}
